### ISSUE TITLE
500 error when BEARER_TOKEN is NULL

### ISSUE THREAD

**Issue by murumkar** [Upala-Corporation/kafka-ims#6]
[2020-01-06 04:53:21,578] ERROR Unhandled exception (io.confluent.rest.exceptions.KafkaExceptionMapper)
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.adobe.ids.dim.security.util.OAuthRestProxyUtil.getIMSBearerTokenJwtFromBearer(OAuthRestProxyUtil.java:30)
	at com.adobe.ids.dim.security.util.OAuthRestProxyUtil.getBearerInformation(OAuthRestProxyUtil.java:63)
	at com.adobe.ids.dim.security.rest.filter.OAuthFilter.filter(OAuthFilter.java:43)
	at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:132)
	at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:68)
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:197)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:269)

**Comment by jairsjunior** [comment]
I will move 2 lines of code from outside to inside try/catch. 
About a jwt validation library i will try some libs to see what is better for us.
