### ISSUE TITLE
java.lang.NullPointerException when I run test with valid token (test.sh)

### ISSUE THREAD

**Issue by murumkar** [Upala-Corporation/kafka-ims#7]
[2020-01-06 04:57:54,738] INFO [Consumer clientId=consumer-2, groupId=my_json_consumer] Setting offset for partition test-topic-0 to the committed offset FetchPosition{offset=2, offsetEpoch=Optional[0], currentLeader=LeaderAndEpoch{leader=broker:9093 (id: 1 rack: null), epoch=0}} (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator)
[2020-01-06 04:57:55,229] INFO 172.24.0.1 - - [06/Jan/2020:04:57:54 +0000] "GET /consumers/my_json_consumer/instances/my_consumer_instance/records HTTP/1.1" 200 82  1016 (io.confluent.rest-utils.requests)

[2020-01-06 04:57:55,266] INFO [Consumer clientId=consumer-2, groupId=my_json_consumer] Member consumer-2-832fc197-1bc9-429c-85da-fda8b34221cf sending LeaveGroup request to coordinator broker:9093 (id: 2147483646 rack: null) (org.apache.kafka.clients.consumer.internals.AbstractCoordinator)
[2020-01-06 04:57:55,266] INFO [Consumer clientId=consumer-2, groupId=my_json_consumer] Member consumer-2-832fc197-1bc9-429c-85da-fda8b34221cf sending LeaveGroup request to coordinator broker:9093 (id: 2147483646 rack: null) (org.apache.kafka.clients.consumer.internals.AbstractCoordinator)
[2020-01-06 04:57:55,276] ERROR Unhandled exception (io.confluent.rest.exceptions.KafkaExceptionMapper)
java.lang.NullPointerException
	at com.adobe.ids.dim.security.rest.filter.OAuthResponseFilter.filter(OAuthResponseFilter.java:31)
	at org.glassfish.jersey.server.ContainerFilteringStage$ResponseFilterStage.apply(ContainerFilteringStage.java:196)
	at org.glassfish.jersey.server.ContainerFilteringStage$ResponseFilterStage.apply(ContainerFilteringStage.java:163)
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)

**Comment by murumkar** [comment]
This happens only sometimes. This may NOT be a bug, just validate to be sure.

**Comment by jairsjunior** [comment]
It happens when the result of call doesn't had a entity on the response, and i had a log that prints this object. 

I will remove this log line, because i only use it during the development.
